# Generated by Django 5.2.1 on 2025-05-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categorya',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
