# Generated by Django 5.2.1 on 2025-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image_review_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
