# Generated by Django 5.2.1 on 2025-05-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
