# Generated by Django 5.2.1 on 2025-05-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danashop', 'UPDATE_SEQS1'),
    ]

    operations = [
    ]
